extensions:
  opamp:
    server:
      ws:
        endpoint: ws://host.docker.internal:4320/v1/opamp
        tls:
          insecure: true
receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 5s
          static_configs:
            - targets: [localhost:8888]
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  remotetap:
    endpoint: 0.0.0.0:12001
exporters:
  debug:

service:
  extensions: [opamp]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [remotetap]
      exporters: [debug]
    traces:
      receivers: [otlp]
      processors: [remotetap]
      exporters: [debug]
    metrics:
      receivers: [prometheus, otlp]
      processors: [remotetap]
      exporters: [debug]